spring:
  application:
    name: spring-native-demo
  kafka:
    bootstrap-servers:
      - ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: "all"
    consumer:
      auto-offset-reset: earliest
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      properties:
        specific.avro.reader: true
    listener:
      ack-mode: manual_immediate
    properties:
      schema.registry.url: ${APP_SCHEMA_REGISTRY_URL:http://localhost:8081}
      auto-register-schemas: true
    streams:
      application-id: "spring-native-demo-kstream"
      properties:
        processing.guarantee: exactly_once_beta
        commit.interval.ms: 50
server:
  port: 7777